### ISSUE TITLE
Dropping webkit

### ISSUE THREAD

**Issue by nicoe** [openlabs/trytond-report-webkit#15]
This is just a suggestion not a bug at all. So you can do whatever you want with it ;).

But I was wondering if you ever though about dropping webkit in favor of something like weasyprint : https://github.com/Kozea/WeasyPrint

**Comment by sharoonthomas** [comment]
@nicoe pr #25 is merged and there is weasy print support for reports that want to implement it. However, it would be nice to have this as a configuration option on reports which I think your new proposal for easily extending report engines build for version 3.5+

Creates issue #26 to handle the migration to new API for tryton 3.6
