### ISSUE TITLE
static files

### ISSUE THREAD

**Issue by hiaselhans** [openlabs/trytond-report-webkit#18]
again, more of a question than a bug...
what do you think is the prefered way to include static files in templates? (stylesheets, backgrounds, images)
as a new tempfile is created relative paths are a bit hard to achieve...

:santa:

**Comment by sharoonthomas** [comment]
@aroraumang whats your preferred approach to this ? and do you have examples you could share ?

**Comment by aroraumang** [comment]
@sharoonthomas @hiaselhans Right now for our use case we are serving from a public URL, but alternatively you could add a json_path to your trytond configuration and the static files will be served from whatever directory you provide in json path when you run trytond.

https://github.com/openlabs/trytond-ceo-report/blob/53d4d89b92e41634979a5f20ee99a05f0c394f8b/ceo_report.html#L10

So, in your case if the file is being served from your local trytond and assuming that it is running on port 8000, you'd use `http://localhost:8000/path/to/your/file`.

**Comment by sharoonthomas** [comment]
For the records patch #21 by @hiaselhans adds a ``modulepath`` filter which should let you use static files bundled with the module itself. To use it:

1. Add the file to the module folder. (Remember to include it in package data in setup.py if your package is distributed and installed to python site packages).
2. Use it in html like ``<img src="{{ 'my_modules/logo.png'|modulepath }}"``.

This needs to be documented. Perhaps in the README.
