### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by hiaselhans** [openlabs/trytond-report-webkit#23]
when installing the package in pips -e mode the package registration point differs from normal installation

steps to reproduce::

```
pip2 install .
cd /
python2
>>>import openlabs_report_webkit
>>>

pip2 install -e .
cd /
python2
>>>import openlabs_report_webkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named openlabs_report_webkit
>>>import report
>>>
```

maybe for proper installation in dev-mode it is required to use the actual package name as source-directory?

**Comment by sharoonthomas** [comment]
@hiaselhans Agree. Do you have any suggestions/ideas as to what the issue is and why the dev package installation is broken ?

**Comment by hiaselhans** [comment]
@sharoonthomas i suspect pip of just creating symbolic links. I dont know pip/setuptools internals good enough to provide a good workaround except for changing the directory name from 'report' to 'openlabs_report_webkit'
Sorry thats the only solution i can offer...
